menu:
  æ–‡ç« :
    éš§é“: /archives/ || anzhiyu-icon-box-archive
    #åˆ†ç±»: /categories/ || anzhiyu-icon-shapes
    æ ‡ç­¾: /tags/ || anzhiyu-icon-tags

  å‹é“¾:
    # å‹äººå¸: /link/ || anzhiyu-icon-link
    # æœ‹å‹åœˆ: /fcircle/ || anzhiyu-icon-artstation
    ç•™è¨€æ¿: /comments/ || anzhiyu-icon-envelope

  æˆ‘çš„:
    éŸ³ä¹é¦†: /music/ || anzhiyu-icon-music
    # è¿½ç•ªé¡µ: /bangumis/ || anzhiyu-icon-bilibili
    # ç›¸å†Œé›†: /album/ || anzhiyu-icon-images
    # å°ç©ºè°ƒ: /air-conditioner/ || anzhiyu-icon-fan

  å…³äº:
    # å…³äºæœ¬äºº: /about/ || anzhiyu-icon-paper-plane
    # é—²è¨€ç¢è¯­: /essay/ || anzhiyu-icon-lightbulb
    éšä¾¿é€›é€›: javascript:toRandomPost() || anzhiyu-icon-shoe-prints1

# navç›¸å…³é…ç½®
nav:
  enable: true
  clock: true
  travelling: false
  menu:
    - title: ç½‘é¡µ
      item:
        - name: åšå®¢
          link: https://blog.aou123.xyz/
          icon: /img/favicon.ico
    - title: ç©å…·é¡¹ç›®
      item:
        - name: Next-Gptæœ¬åœ°éƒ¨ç½²
          link: https://chat.aou123.xyz/
          icon: https://image.anheyu.com/favicon.ico

highlight_theme: mac #  darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
highlight_height_limit: 330 # unit: px
code_word_wrap: false
# Sponsor/reward
reward:
  enable: false
  QR_code:
    - img: 
      link:
      text: å¾®ä¿¡
    - img: 
      link:
      text: æ”¯ä»˜å®

# Avatar (å¤´åƒ)
avatar:
  img: https://s21.ax1x.com/2024/04/25/pkPVgr6.jpg
  effect: true

  # ä¸»è‰²è°ƒç›¸å…³é…ç½®
mainTone:
  enable: true # true or false æ–‡ç« æ˜¯å¦å¯ç”¨è·å–å›¾ç‰‡ä¸»è‰²è°ƒ
  mode: api # cdn/api/both cdnæ¨¡å¼ä¸ºå›¾ç‰‡url+imageAveå‚æ•°è·å–ä¸»è‰²è°ƒï¼Œapiæ¨¡å¼ä¸ºè¯·æ±‚APIè·å–ä¸»è‰²è°ƒï¼Œbothæ¨¡å¼ä¼šå…ˆè¯·æ±‚cdnå‚æ•°ï¼Œæ— æ³•è·å–çš„æƒ…å†µä¸‹å°†è¯·æ±‚APIè·å–ï¼Œå¯ä»¥åœ¨æ–‡ç« å†…é…ç½®main_color: '#3e5658'ï¼Œä½¿ç”¨åå…­è¿›åˆ¶é¢œè‰²ï¼Œåˆ™ä¸ä¼šè¯·æ±‚both/cdn/apiè·å–ä¸»è‰²è°ƒï¼Œè€Œæ˜¯ç›´æ¥ä½¿ç”¨é…ç½®çš„é¢œè‰²
  # é¡¹ç›®åœ°å€ï¼šhttps://github.com/anzhiyu-c/img2color-go
  api: https://img2color-go.vercel.app/api?img= # modeä¸ºapiæ—¶å¯å¡«å†™
  cover_change: true # æ•´ç¯‡æ–‡ç« è·Ÿéšcoverä¿®æ”¹ä¸»è‰²è°ƒ

  # aside (ä¾§è¾¹æ )
# --------------------------------------

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display: # æ§åˆ¶å¯¹åº”è¯¦æƒ…é¡µé¢æ˜¯å¦æ˜¾ç¤ºä¾§è¾¹æ 
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: <div style="line-height:1.38;margin:0.6rem 0;text-align:justify;color:rgba(255, 255, 255, 0.8);">è¿™æœ‰å…³äº<b style="color:#fff">äº§å“ã€è®¾è®¡ã€å¼€å‘</b>ç›¸å…³çš„é—®é¢˜å’Œçœ‹æ³•ï¼Œè¿˜æœ‰<b style="color:#fff">æ–‡ç« ç¿»è¯‘</b>å’Œ<b style="color:#fff">åˆ†äº«</b>ã€‚</div><div style="line-height:1.38;margin:0.6rem 0;text-align:justify;color:rgba(255, 255, 255, 0.8);">ç›¸ä¿¡ä½ å¯ä»¥åœ¨è¿™é‡Œæ‰¾åˆ°å¯¹ä½ æœ‰ç”¨çš„<b style="color:#fff">çŸ¥è¯†</b>å’Œ<b style="color:#fff">æ•™ç¨‹</b>ã€‚</div>
    name_link: /about
  card_announcement:
    enable: true
    content: æ¬¢è¿æ¥çœ‹æˆ‘çš„åšå®¢,æœ‰äº‹è”ç³»é‚®ç®±2832766481@qq.com~
  card_weixin:
    enable: true
    face: ##å¤´åƒä¸‹é¢çš„æ¨¡å— å¯ä»¥æ”¾ä¸¤å¼ å›¾
    backFace: 
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: false
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    sort_order: # Don't modify the setting unless you know how it works
    highlightTags:
      - Hexo
      - å‰ç«¯
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYYå¹´MMæœˆ
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: false
    sort_order: # Don't modify the setting unless you know how it works

# ä½œè€…å¡ç‰‡ çŠ¶æ€
author_status:
  enable: true
  # å¯ä»¥æ˜¯ä»»ä½•å›¾ç‰‡ï¼Œå»ºè®®æ”¾è¡¨æƒ…åŒ…æˆ–è€…emojiå›¾ç‰‡ï¼Œæ•ˆæœéƒ½å¾ˆå¥½ï¼Œ[è¡¨æƒ…åŒ…é€ŸæŸ¥](https://emotion.xiaokang.me/)
  statusImg: "https://bu.dusays.com/2023/08/24/64e6ce9c507bb.png"
  skills:
    - ğŸ¤–ï¸ æ•°ç ç§‘æŠ€çˆ±å¥½è€…
    - ğŸ” åˆ†äº«ä¸çƒ­å¿ƒå¸®åŠ©
    - ğŸ  æ™ºèƒ½å®¶å±…å°èƒ½æ‰‹
    - ğŸ”¨ è®¾è®¡å¼€å‘ä¸€æ¡é¾™
    - ğŸ¤ ä¸“ä¿®äº¤äº’ä¸è®¾è®¡
    - ğŸƒ è„šè¸å®åœ°è¡ŒåŠ¨æ´¾
    - ğŸ§± å›¢é˜Ÿå°ç»„å‘åŠ¨æœº
    - ğŸ’¢ å£®æ±‰äººç‹ è¯ä¸å¤š

# Time difference between publish date and now (ç½‘é¡µè¿è¡Œæ—¶é—´)
# Formal: Month/Day/Year Time or Year/Month/Day Time
runtimeshow:
  enable: true
  publish_date: 4/1/2024 00:00:00

footer:
  owner:
    enable: true
    since: 2024
  custom_text:
  runtime:
    enable: true
    launch_time: 04/01/2024 00:00:00 # ç½‘ç«™ä¸Šçº¿æ—¶é—´
    work_img: https://npm.elemecdn.com/anzhiyu-blog@2.0.4/img/badge/å®‰çŸ¥é±¼-ä¸Šç­æ‘¸é±¼ä¸­.svg
    work_description: ä¸ºå¤©åœ°ç«‹å¿ƒ,ä¸ºç”Ÿæ°‘ç«‹å‘½,ä¸ºå¾€åœ£ç»§ç»å­¦,ä¸ºä¸‡ä¸–å¼€å¤ªå¹³
    offduty_img: https://npm.elemecdn.com/anzhiyu-blog@2.0.4/img/badge/å®‰çŸ¥é±¼-ä¸‹ç­å•¦.svg
    offduty_description: ä¼‘æ¯ä¸­zzz
  # å¾½æ ‡éƒ¨åˆ†é…ç½®é¡¹ https://shields.io/
  # https://img.shields.io/badge/CDN-jsDelivr-orange?style=flat&logo=jsDelivr
  bdageitem:
    enable: false
    list:
      - link: https://hexo.io/ #å¾½æ ‡æŒ‡å‘ç½‘ç«™é“¾æ¥
        shields: https://npm.elemecdn.com/anzhiyu-blog@2.1.5/img/badge/Frame-Hexo.svg #å¾½æ ‡API
        message: åšå®¢æ¡†æ¶ä¸ºHexo_v5.4.0 #å¾½æ ‡æç¤ºè¯­
      - link: https://blog.anheyu.com/
        shields: https://npm.elemecdn.com/anzhiyu-theme-static@1.0.9/img/Theme-AnZhiYu-2E67D3.svg
        message: æœ¬ç«™ä½¿ç”¨AnZhiYuä¸»é¢˜
      # - link: https://www.dogecloud.com/
      #   shields: https://npm.elemecdn.com/anzhiyu-blog@2.2.0/img/badge/CDN-å¤šå‰äº‘-3693F3.svg
      #   message: æœ¬ç«™ä½¿ç”¨å¤šå‰äº‘ä¸ºé™æ€èµ„æºæä¾›CDNåŠ é€Ÿ
      # - link: https://github.com/
      #   shields: https://npm.elemecdn.com/anzhiyu-blog@2.1.5/img/badge/Source-Github.svg
      #   message: æœ¬ç«™é¡¹ç›®ç”±Githubæ‰˜ç®¡
      # - link: http://creativecommons.org/licenses/by-nc-sa/4.0/
      #   shields: https://npm.elemecdn.com/anzhiyu-blog@2.2.0/img/badge/Copyright-BY-NC-SA.svg
      #   message: æœ¬ç«™é‡‡ç”¨çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº«4.0å›½é™…è®¸å¯åè®®è¿›è¡Œè®¸å¯
  socialBar:
    enable: true
    centerImg:
    left:
       - title: email
         link: mailto:2832766481@qq.com
         icon: anzhiyu-icon-envelope
      # - title: å¾®åš
      #   link: https://weibo.com/u/6378063631
      #   icon: anzhiyu-icon-weibo
      # - title: facebook
      #   link: https://www.facebook.com/profile.php?id=100092208016287&sk=about
      #   icon: anzhiyu-icon-facebook1
      # - title: RSS
      #   link: atom.xml
      #   icon: anzhiyu-icon-rss
    right:
       - title: Github
         link: https://github.com/aaaou
         icon: anzhiyu-icon-github
      # - title: Bilibili
      #   link: https://space.bilibili.com/372204786
      #   icon: anzhiyu-icon-bilibili
      # - title: æŠ–éŸ³
      #   link: https://v.douyin.com/DwCpMEy/
      #   icon: anzhiyu-icon-tiktok
      # - title: CC
      #   link: /copyright
      #   icon: anzhiyu-icon-copyright-line
  list:
    enable: false
    randomFriends: 3
    project:
      # - title: æœåŠ¡
      #   links:
      #     - title: 51laç»Ÿè®¡
      #       link: https://v6.51.la/
      #     - title: åå¹´ä¹‹çº¦
      #       link: https://www.foreverblog.cn/
      #     - title: å¼€å¾€
      #       link: https://github.com/travellings-link/travellings
      # - title: ä¸»é¢˜
      #   links:
      #     - title: æ–‡æ¡£
      #       link: /docs/
      #     - title: æºç 
      #       link: https://github.com/anzhiyu-c/hexo-theme-anzhiyu
      #     - title: æ›´æ–°æ—¥å¿—
      #       link: /update/
      # - title: å¯¼èˆª
      #   links:
      #     - title: å³åˆ»çŸ­æ–‡
      #       link: /essay/
      #     - title: å‹é“¾æ–‡ç« 
      #       link: /fcircle/
      #     - title: ç•™è¨€æ¿
      #       link: /comments/
      # - title: åè®®
      #   links:
      #     - title: éšç§åè®®
      #       link: /privacy/
      #     - title: Cookies
      #       link: /cookies/
      #     - title: ç‰ˆæƒåè®®
      #       link: /copyright/
  footerBar:
    enable: true
    authorLink: /
    cc:
      enable: false
      link: /copyright
    linkList:
      - link: https://github.com/anzhiyu-c/hexo-theme-anzhiyu
        text: ä¸»é¢˜
      # - link: https://image.anheyu.com
      #   text: å›¾åºŠ
      # - link: https://beian.miit.gov.cn/
      #   text: æ¹˜ICPå¤‡-xxxxxxxå·
    subTitle:
      enable: true
      # Typewriter Effect (æ‰“å­—æ•ˆæœ)
      effect: true
      # Effect Speed Options (æ‰“å­—æ•ˆæœé€Ÿåº¦å‚æ•°)
      startDelay: 300 # time before typing starts in milliseconds
      typeSpeed: 150 # type speed in milliseconds
      backSpeed: 50 # backspacing speed in milliseconds
      # loop (å¾ªç¯æ‰“å­—)
      loop: true
      # source è°ƒç”¨ç¬¬ä¸‰æ–¹æœåŠ¡
      # source: false å…³é—­è°ƒç”¨
      # source: 1  è°ƒç”¨ä¸€è¨€ç½‘çš„ä¸€å¥è¯ï¼ˆç®€ä½“ï¼‰ https://hitokoto.cn/
      # source: 2  è°ƒç”¨ä¸€å¥ç½‘ï¼ˆç®€ä½“ï¼‰ http://yijuzhan.com/
      # source: 3  è°ƒç”¨ä»Šæ—¥è¯—è¯ï¼ˆç®€ä½“ï¼‰ https://www.jinrishici.com/
      # subtitle ä¼šå…ˆæ˜¾ç¤º source , å†æ˜¾ç¤º sub çš„å†…å®¹
      source: 1
      # å¦‚æœå…³é—­æ‰“å­—æ•ˆæœï¼Œsubtitle åªä¼šæ˜¾ç¤º sub çš„ç¬¬ä¸€è¡Œæ–‡å­—
      sub:
        # - ç”Ÿæ´»æ˜æœ—&#44; ä¸‡ç‰©å¯çˆ±&#44; äººé—´å€¼å¾—&#44; æœªæ¥å¯æœŸ.
    
    # é¦–é¡µé¡¶éƒ¨ç›¸å…³é…ç½®
home_top:
  enable: true # å¼€å…³
  timemode: date #date/updated
  title: å…´å°½æ‚²æ¥
  subTitle: è¯†ç›ˆè™šä¹‹æœ‰æ•°
  siteText: anheyu.com
  category:
    - name: æ–‡ç« æ€»è§ˆ
      path: /archives/
      shadow: var(--anzhiyu-shadow-blue)
      class: blue
      icon: anzhiyu-icon-dove
    - name: å¬å¬éŸ³ä¹
      path: /music/
      shadow: var(--anzhiyu-shadow-red)
      class: red
      icon: anzhiyu-icon-fire
    - name: å¼€å‘æ•™ç¨‹
      path: /categories/å¼€å‘æ•™ç¨‹/
      shadow: var(--anzhiyu-shadow-green)
      class: green
      icon: anzhiyu-icon-book
  default_descr: å†æ€ä¹ˆçœ‹æˆ‘ä¹Ÿä¸çŸ¥é“æ€ä¹ˆæè¿°å®ƒçš„å•¦ï¼
  swiper:
    enable: false
    swiper_css: https://npm.elemecdn.com/anzhiyu-theme-static@1.0.0/swiper/swiper.min.css #swiper cssä¾èµ–
    swiper_js: https://npm.elemecdn.com/anzhiyu-theme-static@1.0.0/swiper/swiper.min.js #swiper jsä¾èµ–
  banner:
    tips: Under Construction
    title: åšå®¢ä»åœ¨å»ºè®¾ä¸­...å•å‡»å­¦ä¹ ~
    image: https://s21.ax1x.com/2024/05/20/pkKYlwj.jpg
    link: https://leetcode.cn/problemset/all-code-essentials/?listId=2cktkvj&page=1


# Loading Animation (åŠ è½½åŠ¨ç”»)
preloader:
  enable: true
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  # else all
  source: 3
  # pace theme (see https://codebyzach.github.io/pace/)
  pace_css_url:
  avatar: https://s21.ax1x.com/2024/04/25/pkPVgr6.jpg


#envelope_comment
#seehttps://akilar.top/posts/e2d3c450/
envelope_comment:
  enable: true #æ§åˆ¶å¼€å…³
  custom_pic:
    cover: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/violet.jpg #ä¿¡ç¬ºå¤´éƒ¨å›¾ç‰‡
    line: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/line.png #ä¿¡ç¬ºåº•éƒ¨å›¾ç‰‡
    beforeimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/before.png # ä¿¡å°å‰åŠéƒ¨åˆ†
    afterimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/after.png # ä¿¡å°ååŠéƒ¨åˆ†
  message: #ä¿¡ç¬ºæ­£æ–‡ï¼Œå¤šè¡Œæ–‡æœ¬ï¼Œå†™æ³•å¦‚ä¸‹
    - æœ‰ä»€ä¹ˆæƒ³é—®çš„ï¼Ÿ
    - æœ‰ä»€ä¹ˆæƒ³è¯´çš„ï¼Ÿ
    - æœ‰ä»€ä¹ˆæƒ³åæ§½çš„ï¼Ÿ
    - å“ªæ€•æ˜¯æœ‰ä»€ä¹ˆæƒ³åƒçš„ï¼Œéƒ½å¯ä»¥å‘Šè¯‰æˆ‘å“¦~
  bottom: è‡ªåŠ¨ä¹¦è®°äººå¶ç«­è¯šä¸ºæ‚¨æœåŠ¡ï¼ #ä»…æ”¯æŒå•è¡Œæ–‡æœ¬
  height: #1024pxï¼Œä¿¡å°åˆ’å‡ºçš„é«˜åº¦
  path: #ã€å¯é€‰ã€‘comments çš„è·¯å¾„åç§°ã€‚é»˜è®¤ä¸º commentsï¼Œç”Ÿæˆçš„é¡µé¢ä¸º comments/index.html
  front_matter: #ã€å¯é€‰ã€‘commentsé¡µé¢çš„ front_matter é…ç½®
    title: ç•™è¨€æ¿
    comments: true
    top_img: false
    type: envelope


comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Valine/Waline/Twikoo/
  use: Twikoo # ,Waline # Twikoo/Waline
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  count: true # Display comment count in post's top_img
  card_post_count: false # Display comment count in Home Page

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
  envId: https://twikoo.aou123.xyz
  region:
  visitor: true
  option:

# Chat Button [recommend]
# It will create a button in the bottom right corner of website, and hide the origin button
chat_btn: true
# The origin chat button is displayed when scrolling up, and the button is hidden when scrolling down
chat_hide_show: true
# chatra
# https://chatra.io/
chatra:
  enable: true
  id: Dn7LJo6BH552fmunJ

# social settings (ç¤¾äº¤å›¾æ ‡è®¾ç½®)
# formal:
#   name: link || icon
social:
   Github: https://github.com/aaaou|| anzhiyu-icon-github
  # BiliBili: https://space.bilibili.com/372204786 || anzhiyu-icon-bilibili

icons:
  ali_iconfont_js: # é˜¿é‡Œå›¾æ ‡symbol å¼•ç”¨é“¾æ¥ï¼Œä¸»é¢˜ä¼šè¿›è¡ŒåŠ è½½ symbol å¼•ç”¨
  fontawesome: false #æ˜¯å¦å¯ç”¨fontawesome6å›¾æ ‡
  fontawesome_animation_css: #fontawesome_animation å¦‚æœæœ‰å°±ä¼šåŠ è½½ï¼Œç¤ºä¾‹å€¼ï¼šhttps://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@1.0.17/lib/assets/font-awesome-animation.min.css


busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# Console - Newest Comments
newest_comments:
  enable: true
  sort_order: # Don't modify the setting unless you know how it works
  limit: 6
  storage: 10 # unit: mins, save data to localStorage
  avatar: true

translate:
  enable: true
  # é»˜è®¤æŒ‰é’®æ˜¾ç¤ºæ–‡å­—(ç½‘ç«™æ˜¯ç®€ä½“ï¼Œåº”è®¾ç½®ä¸º'default: ç¹')
  default: ç®€
  #ç½‘ç«™é»˜è®¤è¯­è¨€ï¼Œ1: ç¹ä½“ä¸­æ–‡, 2: ç®€ä½“ä¸­æ–‡
  defaultEncoding: 1
  #å»¶è¿Ÿæ—¶é—´,è‹¥ä¸åœ¨å‰, è¦è®¾å®šå»¶è¿Ÿç¿»è¯‘æ—¶é—´, å¦‚100è¡¨ç¤º100ms,é»˜è®¤ä¸º0
  translateDelay: 0
  #å½“æ–‡å­—æ˜¯ç®€ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToTraditionalChinese: "ç¹"
  #å½“æ–‡å­—æ˜¯ç¹ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToSimplifiedChinese: "ç®€"

readmode: true

# dark mode
darkmode:
  enable: true
  # Toggle Button to switch dark/light mode
  button: true
  # Switch dark/light mode automatically (è‡ªåŠ¨åˆ‡æ¢ dark modeå’Œ light mode)
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: 1
  # Set the light mode time. The value is between 0 and 24. If not set, the default value is 6 and 18
  start: # 8
  end: # 22

# åŒæ æ–‡ç« 
article_double_row: true


# æ¬¢è¿è¯­é…ç½®
greetingBox:
  enable: true #å¼€å¯åå¿…é¡»é…ç½®ä¸‹é¢çš„listå¯¹åº”çš„æ—¶é—´æ®µï¼Œä¸ç„¶ä¼šå‡ºç°å°ç™½æ¡
  default: æ™šä¸Šå¥½ğŸ‘‹
  list:
    - greeting: æ™šå®‰ğŸ˜´
      startTime: 0
      endTime: 5
    - greeting: æ—©ä¸Šå¥½é¸­ğŸ‘‹, ç¥ä½ ä¸€å¤©å¥½å¿ƒæƒ…ï¼
      startTime: 6
      endTime: 9
    - greeting: ä¸Šåˆå¥½ğŸ‘‹, çŠ¶æ€å¾ˆå¥½ï¼Œé¼“åŠ±ä¸€ä¸‹ï½
      startTime: 10
      endTime: 10
    - greeting: 11ç‚¹å¤šå•¦, åœ¨åšæŒä¸€ä¸‹å°±åƒé¥­å•¦ï½
      startTime: 11
      endTime: 11
    - greeting: åˆå®‰ğŸ‘‹, å®è´
      startTime: 12
      endTime: 14
    - greeting: ğŸŒˆå……å®çš„ä¸€å¤©è¾›è‹¦å•¦ï¼
      startTime: 14
      endTime: 18
    - greeting: 19ç‚¹å–½, å¥–åŠ±ä¸€é¡¿ä¸°ç››çš„å¤§é¤å§ğŸ”ã€‚
      startTime: 19
      endTime: 19
    - greeting: æ™šä¸Šå¥½ğŸ‘‹, åœ¨å±äºè‡ªå·±çš„æ—¶é—´å¥½å¥½æ”¾æ¾ğŸ˜Œ~
      startTime: 20
      endTime: 24


local_search:
  enable: true
  preload: false
  CDN:

mathjax:
  enable: true
  per_page: false

# KaTeX
katex:
  enable: false
  per_page: false
  hide_scrollbar: true
